#!/bin/sh
# ============================================================================
# test ups unconfigure
# ============================================================================
cd $UPS_DIR/test/scripts/unconfigure
$UPS_DIR/test/ups_test << EOD

quit
EOD
