#!/bin/sh
# ============================================================================
# test ups compile 
# ============================================================================
PRODUCTS="$UPS_DIR/test/scripts/compile/db1"; export PRODUCTS
cd $UPS_DIR/test/scripts/compile/log
$UPS_DIR/test/ups_test << EOD
#
#
configure rover v1_0
upsact_process_commands -out rover.out -diff rover.in setup rover v1_0 
#
quit
EOD
diff rover.out.sh rover.in.sh
diff rover.out.csh rover.in.csh
