#!/bin/sh
# ============================================================================
# test ups list
# ============================================================================
PRODUCTS=""
cd $UPS_DIR/test/scripts/list
$UPS_DIR/test/ups_test << EOD
#ups_echo "================================================================="
#
#
# all instances of all products sorted alphabetically
#
list -out all.out -diff all.in -z db1 -a
#
# long listing  - let's see it all for an instance with not much, and for
#   	and instance with the whole shabang.
#
list -out long.out -diff long.in -z db1 -a -l spot v2_0
#
# test getting keywords
#
list -out /dev/null -z db1 -q long spot v2_0 -K "BLAH" -estatus UPS_INVALID_KEYWORD
list -out key1.out -diff key1.in -z db1 -q long spot v2_0 -K "ARCHIVE_FILE:AUTHORIZED_NODES:_DUMMY:DESCRIPTION"
list -out key2.out -diff key2.in -z db1 -a lassie -K +
list -out key3.out -diff key3.in -z db1 -a lassie -K +:DECLARED
#
# need to test multiple databases
quit
EOD
