#!/bin/ksh
# ============================================================================
# test the file routines
# ============================================================================
touch dummy.file
cd $ERUPT_DIR/test/scripts/file
$ERUPT_DIR/test/ups_test << EOD
#ups_echo "================================================================="
upsfil_read_file ../database/dog_v2_0.version
upsfil_write_file dog_v2_0.version.out
upsfil_read_file ../database/dog_v2_0_1.table
upsfil_write_file dog_v2_0_1.table.out
upsfil_write_file -status UPS_OPEN_FILE /junk/junk/junk
upserr_clear
upsfil_write_file -status UPS_UNKNOWN_FILETYPE /junk/junk/junk
upserr_clear
upsfil_read_file -status UPS_OPEN_FILE blah
upserr_clear
upsfil_read_file -status UPS_READ_FILE dummy.file
upserr_clear
quit
EOD
diff ../database/dog_v2_0.version dog_v2_0.version.out
diff ../database/dog_v2_0_1.table dog_v2_0_1.table.out
rm dummy.file
