#!/bin/sh
# ============================================================================
# test ups configure
# ============================================================================
cd $UPS_DIR/test/scripts/configure
$UPS_DIR/test/ups_test << EOD

quit
EOD
