#!/bin/sh
# ============================================================================
# test ups depend
# ============================================================================
cd $UPS_DIR/test/scripts/depend/log
$UPS_DIR/test/ups_test << EOD 

ups_echo "===Test 1"
depend bee3 v2_0 -f NULL -z ../db1 -K DECLARER -out bee1.out -diff bee1.in
ups_echo "===Test 2"
depend bee3 v2_0 -f NULL -z ../db1 -K ACTION -status UPS_INVALID_KEYWORD
ups_echo "===Test 3" 
depend bee3 v2_0  -f NULL  -z ../db1 -m bee5.table -out bee2.out -diff bee2.in
ups_echo "===Test 4"
depend bee3   v2_0   -f NULL -z ../db1 -M ../db1/bee3 -out bee3.out -diff bee3.in



quit
EOD

