#!/bin/sh
# ============================================================================
# test ups compile 
# ============================================================================
PRODUCTS="$UPS_DIR/test/scripts/compile/db1"; export PRODUCTS
cd $UPS_DIR/test/scripts/compile
$UPS_DIR/test/ups_test << EOD
#
#
configure rover v1_0
#
# test most switches
#
#
#
#declare spot v1_0 -f NULL -r \${UPS_DIR}/test/scripts/declare/products/spot -M ups -m spot.table -c -d -o -t -n -g leash -actout log/tmp.out -out log/spot1.out -diff log/spot1.in
#declare spot v1_0 -f NULL -c -d -o -t -n -g leash -actout log/tmp.out -out log/spot2.out -diff log/spot2.in 
#declare spot v2_0 -f IRIX -r \${UPS_DIR}/test/scripts/declare/products/spot -C -c -M ups -m spot.table 
quit
EOD
