#!/bin/sh
# ============================================================================
# test the get routines
# ============================================================================
unset PRODUCTS
cd $UPS_DIR/test/scripts/get
env SHELL=/bin/csh $UPS_DIR/test/ups_test << EOD
#=================================================================
#
upsget_translation -z ../list/db1 -f NULL -q "nodbg:opt" lassie v2_0 -e -O "-blah" -out get1.out -diff get1.in
upsget_translation -z ../list/db1 -f NULL -q "nodbg:opt" lassie v2_0 -r /dog/house -out get2.out -diff get2.in
upsget_allout -z ../list/db1 -f NULL -q "nodbg:opt" lassie v2_0 -out get3.out -diff get3.in
quit
EOD
env SHELL=/bin/sh $UPS_DIR/test/ups_test << EOD2
upsget_allout -z ../list/db1 -f NULL -q "nodbg:opt" lassie v2_0 -out get4.out -diff get4.in
quit
EOD2
