#!/bin/sh
# ============================================================================
# test ups copy
# ============================================================================
cd $UPS_DIR/test/scripts/copy
$UPS_DIR/test/ups_test << EOD

ups copy bee1 v1_0 -O "bee3 v4_0" -z copy/db2 -f NULL -v
ups copy bee1 v1_0 -f NULL -z copy/db2
quit
EOD
