#!/bin/sh 
# ============================================================================
# test ups declare
# ============================================================================
PRODUCTS="$UPS_DIR/test/scripts/declare/dbclean"; export PRODUCTS
rm -rf $PRODUCTS
mkdir $PRODUCTS
cd $UPS_DIR/test/scripts/declare
$UPS_DIR/test/ups_test << EOD
#
#
declare rover -status UPS_INVALID_SPECIFICATION 
declare rover v1_0 -f NULL -r /tmp
declare rover v1_0 -f NULL -r /tmp -status UPS_INVALID_SPECIFICATION
declare rover v1_0 -f IRIX -g leash -r /tmp
#declare rover v1_0 -f IRIX -g leash
upserr_clear
#
# test most switches
#
declare rover v2_0 -f NULL -A backyard -b mycompile -D akc@kennel -g leash -L -m tablefile -M /tabledir -O "-blah" -q"red" -r /dog/house -T ftp:/tarfile -u /tmp -U /ups 
#
# make sure actions are executed
#
declare spot v1_0 -f NULL -r '$UPS_DIR/test/scripts/declare/products/spot' -M ups -m spot.table -c -d -o -t -n -g leash
declare spot v1_0 -f NULL -c -d -o -t -n -g leash 
#declare spot v2_0 -C -c -r $UPS_DIR/test/scripts/declare/spot -m spot.table
quit
EOD
diff dbclean/rover/leash.chain dbcmp/rover | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/rover/v1_0.version dbcmp/rover | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/rover/v2_0.version dbcmp/rover | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/ dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
