#!/bin/sh
# ============================================================================
# test ups undeclare
# ============================================================================
cd $UPS_DIR/test/scripts/undeclare
$UPS_DIR/test/ups_test << EOD

quit
EOD
