#!/bin/sh
# ============================================================================
# test ups depend
# ============================================================================
cd $UPS_DIR/test/scripts/depend
$UPS_DIR/test/ups_test << EOD
depend snoopy v1_0 -f NULL -z ./db1 -K DECLARER
ups_echo ====
depend snoopy v1_0 -f NULL -z ./db1 -K ACTION
  ups_echo ====
depend snoopy      -f NUL L -z ./db1 -m sn1.table
ups_echo ====
depend snoopy      -f NULL -z ./db1 -M ./db1/lassie/snoopy.table
ups_echo ====

depend rover -z ./db1 -f NULL v2_0

quit
EOD
